name: Build and Deploy on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install

      - name: Archive JAR
        run: mv target/*.jar application.jar

      - name: Add EC2 Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          # Write the SSH key to a temporary file
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem  # Set appropriate permissions
      
          # Use scp to copy the JAR file to the EC2 instance
          scp -i ec2_key.pem application.jar $EC2_USER@$EC2_HOST:/application.jar
      
          # Execute commands on the EC2 instance
          ssh -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar /application.jar > app.log 2>&1 &
          EOF
      
          # Clean up the temporary key file
          rm ec2_key.pem
